<?php
http_response_code(200);
header('Content-Type: application/json');

$data = [
    'sorts' => [
        [
            'token' => 'T637407508254941795_Curated,N_6ac5',
            'name' => 'Curated_96',
            'displayName' => 'Most Engaging',
            'gameSetTargetId' => 96,
            'timeOptionsAvailable' => false,
            'genreOptionsAvailable' => true,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
        [
            'token' => 'T637407508254941795_Curated,R_fc02',
            'name' => 'Curated_60',
            'displayName' => 'Up-and-Coming',
            'gameSetTargetId' => 60,
            'timeOptionsAvailable' => false,
            'genreOptionsAvailable' => true,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
        [
            'token' => 'T637407508254941795_Popular,N_f7de',
            'name' => 'Popular',
            'displayName' => 'Popular',
            'gameSetTargetId' => null,
            'timeOptionsAvailable' => false,
            'genreOptionsAvailable' => true,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
        [
            'token' => 'T637407508254941795_TopRated,N_66bf',
            'name' => 'TopRated',
            'displayName' => 'Top Rated',
            'gameSetTargetId' => null,
            'timeOptionsAvailable' => true,
            'genreOptionsAvailable' => true,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
        [
            'token' => 'T637407508254941795_TopRetaining,N_3bc',
            'name' => 'TopRetaining',
            'displayName' => 'Recommended',
            'gameSetTargetId' => null,
            'timeOptionsAvailable' => false,
            'genreOptionsAvailable' => true,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
        [
            'token' => 'T637407508254941795_Curated,R_fc02',
            'name' => 'Curated_71',
            'displayName' => 'Play Together (Free Private Servers)',
            'gameSetTargetId' => 71,
            'timeOptionsAvailable' => false,
            'genreOptionsAvailable' => true,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
        [
            'token' => 'T637407508254941795_Curated,R_fc02',
            'name' => 'Curated_67',
            'displayName' => 'Learn & Explore',
            'gameSetTargetId' => 67,
            'timeOptionsAvailable' => false,
            'genreOptionsAvailable' => true,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
        [
            'token' => 'T637407508254941795_Featured,R_b70b',
            'name' => 'Featured',
            'displayName' => 'Featured',
            'gameSetTargetId' => null,
            'timeOptionsAvailable' => false,
            'genreOptionsAvailable' => false,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
        [
            'token' => 'T637407508254941795_Curated,N_6ac5',
            'name' => 'Curated_94',
            'displayName' => 'Popular Among Premium',
            'gameSetTargetId' => 94,
            'timeOptionsAvailable' => false,
            'genreOptionsAvailable' => true,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
        [
            'token' => 'T637407508254941795_Curated,R_fc02',
            'name' => 'Curated_5',
            'displayName' => 'Rthro',
            'gameSetTargetId' => 5,
            'timeOptionsAvailable' => false,
            'genreOptionsAvailable' => true,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
        [
            'token' => 'T637407508254941795_TopGrossing,N_6e7c',
            'name' => 'TopGrossing',
            'displayName' => 'Top Earning',
            'gameSetTargetId' => null,
            'timeOptionsAvailable' => false,
            'genreOptionsAvailable' => true,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
        [
            'token' => 'T637407508254941795_Curated,N_6ac5',
            'name' => 'Curated_81',
            'displayName' => 'Players Love',
            'gameSetTargetId' => 81,
            'timeOptionsAvailable' => false,
            'genreOptionsAvailable' => true,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
        [
            'token' => 'T637407508254941795_Curated,R_fc02',
            'name' => 'Curated_64',
            'displayName' => 'Roleplay',
            'gameSetTargetId' => 64,
            'timeOptionsAvailable' => false,
            'genreOptionsAvailable' => true,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
        [
            'token' => 'T637407508254941795_Curated,R_fc02',
            'name' => 'Curated_63',
            'displayName' => 'Adventure',
            'gameSetTargetId' => 63,
            'timeOptionsAvailable' => false,
            'genreOptionsAvailable' => true,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
        [
            'token' => 'T637407508254941795_Curated,R_fc02',
            'name' => 'Curated_62',
            'displayName' => 'Fighting',
            'gameSetTargetId' => 62,
            'timeOptionsAvailable' => false,
            'genreOptionsAvailable' => true,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
        [
            'token' => 'T637407508254941795_Curated,R_fc02',
            'name' => 'Curated_56',
            'displayName' => 'Obby',
            'gameSetTargetId' => 56,
            'timeOptionsAvailable' => false,
            'genreOptionsAvailable' => true,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
        [
            'token' => 'T637407508254941795_Curated,R_fc02',
            'name' => 'Curated_58',
            'displayName' => 'Tycoon',
            'gameSetTargetId' => 58,
            'timeOptionsAvailable' => false,
            'genreOptionsAvailable' => true,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
        [
            'token' => 'T637407508254941795_Curated,R_fc02',
            'name' => 'Curated_57',
            'displayName' => 'Simulator',
            'gameSetTargetId' => 57,
            'timeOptionsAvailable' => false,
            'genreOptionsAvailable' => true,
            'numberOfRows' => 1,
            'numberOfGames' => 0,
            'isDefaultSort' => true,
            'contextUniverseId' => null,
            'contextCountryRegionId' => null,
            'tokenExpiryInSeconds' => 3600.0,
        ],
    ],

    'timeFilters' => [
        ['token' => 'T637407508254941795_Now_4344',      'name' => 'Now',       'tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_PastDay_36d0',  'name' => 'PastDay',   'tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_PastWeek_3062', 'name' => 'PastWeek',  'tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_PastMonth_c1b4','name' => 'PastMonth', 'tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_AllTime_6c2f',  'name' => 'AllTime',   'tokenExpiryInSeconds' => 3600.0],
    ],

    'genreFilters' => [
        ['token' => 'T637407508254941795_1_4d8b',  'name' => 'All',          'tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_19_d6ef', 'name' => 'Building',     'tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_11_b46d', 'name' => 'Horror',       'tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_7_c46b',  'name' => 'Town and City','tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_17_3d8d', 'name' => 'Military',     'tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_15_852c', 'name' => 'Comedy',       'tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_8_d358',  'name' => 'Medieval',     'tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_13_ccc',  'name' => 'Adventure',    'tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_9_2f09',  'name' => 'Sci-Fi',       'tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_12_f09d', 'name' => 'Naval',        'tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_20_c78',  'name' => 'FPS',          'tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_21_f029', 'name' => 'RPG',          'tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_14_797d', 'name' => 'Sports',       'tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_10_483c', 'name' => 'Fighting',     'tokenExpiryInSeconds' => 3600.0],
        ['token' => 'T637407508254941795_16_c1dc', 'name' => 'Western',      'tokenExpiryInSeconds' => 3600.0],
    ],

    'gameFilters' => [
        ['token' => 'T637407508254941795_Any_aa4f',     'name' => 'Any',     'tokenExpiryInSeconds' => 3600],
        ['token' => 'T637407508254941795_Classic_cb90', 'name' => 'Classic', 'tokenExpiryInSeconds' => 3600],
    ],

    'pageContext' => [
        'pageId'       => 'e20312b2-b6da-496d-975c-ae7fc5b6cbd0',
        'isSeeAllPage' => null,
    ],
];

echo json_encode($data);